feat: restart connection changes
Drafteame/cassandra-builder pull request #11
Opened 2023-02-21 16:35 UTC by andihaskel

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.

## Task Context

### What is the current behavior?

### What is the new behavior?

### Additional Context

## Checklist

### How was it tested?

- [ ] unit
- [ ] integration
- [ ] other (specify)

### Updated services

- [ ] Does your code follow the project style guide?
- [ ] Have you added tests that cover the changes and run them?

2023-02-21 16:59 UTC, danteay requested changes

2023-02-21 16:59 UTC, danteay commented on qb/qdelete/delete_exec.go
> +	runner := runner.New(dq.client)
sigiero cambiar el nombre para que no colicione con el nombre de paquete:

```suggestion
	run := runner.New(dq.client)
```

2023-02-21 16:59 UTC, danteay commented on qb/qselect/select_exec.go
> +	runner := runner.New(q.client)
igual aca:

```suggestion
	run := runner.New(q.client)
```

2023-02-21 16:59 UTC, danteay commented on runner/runner.go
> +}
Esta funcion no tiene qu regresar el iter porque de ser asi nunca obtenemos el error sino ya fuera de la ejecucion.

El error que buscamos se dispara cuando hacemos `iter.Close()` por lo que lo ultimo que hace la funcion `execFn` debe ser justo el cerrar el iter.

Esto va a obligar a que recorramos el iterador dentro de la funcion exec para guardar los resultados de alguna forma.

2023-02-21 19:44 UTC, danteay requested changes

2023-02-21 19:44 UTC, danteay commented on qb/qcount/tests/count_exec_test.go
> +package qcounttest
esto mejor dejarlo al mismo nivel del paquete `qcount` en lugar de tener en u sub nivel

2023-02-21 19:44 UTC, danteay commented on qb/qcount/count.go
> +}
si los test los ponemos en el mismo nivel en lugar de ponerlos en una carpeta `tests` estos getters no son necesarios, al final solo se usan dentro de los test y en el uso regular del builder realmente no se ocupan.

2023-02-21 19:44 UTC, danteay commented on qb/qcount/tests/count_test.go
> +package qcounttest
no ponerlos en un sub nivel

2023-02-21 19:44 UTC, danteay commented on qb/qinsert/insert.go
> +}
mismo tema que el anterior, estos metodos no se usan fuera del test

2023-02-21 19:44 UTC, danteay commented on qb/qinsert/tests/insert_exec_test.go
> +package qinserttest
no poner en sub nivel

2023-02-21 19:44 UTC, danteay commented on qb/qinsert/tests/insert_test.go
> +package qinserttest
no poner en sub nivel

2023-02-21 19:44 UTC, danteay commented on qb/qupdate/tests/update_exec_test.go
> +package qupdatetest
no poner en sub nivel

2023-02-21 19:44 UTC, danteay commented on qb/qupdate/tests/update_test.go
> +package qupdatetest
no poner en sub nivel

2023-02-21 19:44 UTC, danteay commented on qb/qupdate/update.go
> +}
no son requeridos fuera del testing

2023-02-22 14:12 UTC, danteay approved these changes

2023-02-24 14:42 UTC, gabrielbursztein2 requested changes

2023-02-24 14:42 UTC, gabrielbursztein2 commented on qb/qb.go
> +func NewClientWithSession(session *gocql.Session, conf models.Config) (Client, error) {
Por que sacamos estos metodos de `qb/client.go`? 
La idea de este archivo es solamente definir la interfaz.

2023-02-24 14:42 UTC, gabrielbursztein2 commented on qb/qcount/count_exec.go
> -	}
La idea del `Debug` es que imprima las queries para tener mas control.
Podemos volver a incluirlo?

2023-02-24 14:42 UTC, gabrielbursztein2 commented on qb/runner/mocks/client.go
> +// Code generated by mockery v2.16.0. DO NOT EDIT.
Para mantener consistencia con el game-engine pondría este archivo en `test/mocks/client.go`

2023-02-24 14:42 UTC, gabrielbursztein2 commented on qb/runner/runner.go
> +	execFn := func() error {
Elimina este espacio

2023-02-24 14:42 UTC, gabrielbursztein2 commented on qb/runner/runner.go
> +			//TODO: handle error
Por que no manejamos el error?

2023-02-24 14:42 UTC, gabrielbursztein2 commented on qb/runner/runner.go
> +		}
Como sabemos que es aca donde sale este error?

2023-02-24 14:43 UTC, gabrielbursztein2 commented on qb/models/config.go
> +package models
Mas que models le pondría `config` al package

2023-02-24 15:33 UTC, andihaskel commented on qb/runner/runner.go
> +			//TODO: handle error
deberiamos mandarlo a sentry o algo. Esto va a intentar hacer un restart N cantidad de attempts, si falla con alguno de las errores de execFunc despues de los intentos lo va a retornar

2023-02-24 15:41 UTC, andihaskel commented on qb/runner/runner.go
> +		}
https://github.com/gocql/gocql/issues/915#issuecomment-1305955277

2023-02-24 15:47 UTC, andihaskel commented on qb/models/config.go
> +package models
no me parece mal models, no tiene configuracion mas que la estructura

2023-02-27 16:51 UTC, gabrielbursztein2 commented on qb/runner/runner.go
> +			//TODO: handle error
Digo, no deberíamos omitir el error que devueve el `r.client.Restart()`

2023-02-27 16:53 UTC, gabrielbursztein2 commented on qb/client.go
> +func getSession(c models.Config) (*gocql.Session, error) {
Podemos ponerle `createSession`? 

`getSession` me suena mas a un singleton

2023-02-27 16:55 UTC, gabrielbursztein2 commented on qb/client.go
> +}
```suggestion
func NewClientWithSession(session *gocql.Session, conf models.Config) Client {
	return &client{
		session:    session,
		config:     conf,
		canRestart: false,
	}
}
```

2023-02-27 16:59 UTC, danteay commented on qb/runner/runner.go
> +			//TODO: handle error
se quito porque alli esta el dema del log de debug, tuvimos probelas de serializacion porque el cliente tiene la config que a si vez tiene una propiedad que no es serializable a json `PrintFn` y esto generaba un panic en el framework. la idea es que pongamos un sistema de logging mas estandarizado como lo tiene por ejemplo gorm que es una interface independiente modificable.

2023-02-27 20:30 UTC, gabrielbursztein2 commented on qb/qcount/count_test.go
> +		return
```suggestion
		t.Fatalf("exp: test2 got: %v", q.table)
```

2023-02-27 20:32 UTC, gabrielbursztein2 commented on qb/qinsert/insert_exec_test.go
> +		query := q.Build()
No te deja usarlo si es privado? Esta dentro del mismo paquete 🤔

2023-02-27 22:40 UTC, gabrielbursztein2 approved these changes
🥇

2023-02-28 14:17 UTC, merged